import { Component } from '@angular/core';
import { Root } from './model';

@Component({
  selector: 'app-speed-test',
  standalone: true,
  imports: [],
  templateUrl: './speed-test.component.html',
  styleUrl: './speed-test.component.scss'
})
export class SpeedTestComponent {
data:Root[] = [];
  constructor(){
    this.data = [
      {
          "pilot_number": "7971317890",
          "campaignid": "94731",
          "total_dial_history": 19796,
          "total_success": 549,
          "total_failure": 19247,
          "success_per": 3,
          "failure_per": 97,
          "retry_history_0": 0,
          "retry_history_1": null,
          "retry_history_2": null,
          "total_dial_count": 19797,
          "retry_dial_0": 0,
          "retry_dial_1": null,
          "retry_dial_2": null,
          "callerId": "7971318862",
          "service_group": "AHM-V1",
          'retry0':[]

      },
      {
          "pilot_number": "7971728290",
          "campaignid": "94731",
          "total_dial_history": 19797,
          "total_success": 550,
          "total_failure": 19247,
          "success_per": 3,
          "failure_per": 97,
          "retry_history_0": 0,
          "retry_history_1": null,
          "retry_history_2": null,
          "total_dial_count": 19797,
          "retry_dial_0": 0,
          "retry_dial_1": null,
          "retry_dial_2": null,
          "callerId": "7971729261",
          "service_group": "AHM-V4",
          'retry0':[]

      },
      {
          "pilot_number": "8645378230",
          "campaignid": "94731",
          "total_dial_history": 9890,
          "total_success": 232,
          "total_failure": 9658,
          "success_per": 2,
          "failure_per": 98,
          "retry_history_0": 0,
          "retry_history_1": null,
          "retry_history_2": null,
          "total_dial_count": 9890,
          "retry_dial_0": 0,
          "retry_dial_1": null,
          "retry_dial_2": null,
          "callerId": "8645715030",
          "service_group": "VJVD-V8",
          'retry0':[]

      },
      {
          "pilot_number": "8645371111",
          "campaignid": "94731",
          "total_dial_history": 9898,
          "total_success": 240,
          "total_failure": 9658,
          "success_per": 2,
          "failure_per": 98,
          "retry_history_0": 0,
          "retry_history_1": null,
          "retry_history_2": null,
          "total_dial_count": 9899,
          "retry_dial_0": 0,
          "retry_dial_1": null,
          "retry_dial_2": null,
          "callerId": "8645375939",
          "service_group": "VJVD-V6",
          'retry0':[]

      },
      {
          "pilot_number": "7313772590",
          "campaignid": "94731",
          "total_dial_history": 9984,
          "total_success": 279,
          "total_failure": 9705,
          "success_per": 3,
          "failure_per": 97,
          "retry_history_0": 0,
          "retry_history_1": null,
          "retry_history_2": null,
          "total_dial_count": 9984,
          "retry_dial_0": 0,
          "retry_dial_1": null,
          "retry_dial_2": null,
          "callerId": "7313773563",
          "service_group": "IND-V3",
          'retry0':[]

      },
      {
          "pilot_number": "7313791587",
          "campaignid": "94731",
          "total_dial_history": 9899,
          "total_success": 278,
          "total_failure": 9621,
          "success_per": 3,
          "failure_per": 97,
          "retry_history_0": 0,
          "retry_history_1": null,
          "retry_history_2": null,
          "total_dial_count": 9899,
          "retry_dial_0": 0,
          "retry_dial_1": null,
          "retry_dial_2": null,
          "callerId": "7313792565",
          "service_group": "IND-V2",
          'retry0':[]

      },
      {
          "pilot_number": "7971743290",
          "campaignid": "94731",
          "total_dial_history": 19797,
          "total_success": 0,
          "total_failure": 19797,
          "success_per": 0,
          "failure_per": 100,
          "retry_history_0": 0,
          "retry_history_1": null,
          "retry_history_2": null,
          "total_dial_count": 19797,
          "retry_dial_0": 0,
          "retry_dial_1": null,
          "retry_dial_2": null,
          "callerId": "7971744265",
          "service_group": "AHM-V3",
          'retry0':[]

      },
      {
          "pilot_number": "7971304745",
          "campaignid": "94731",
          "total_dial_history": 19797,
          "total_success": 509,
          "total_failure": 19288,
          "success_per": 3,
          "failure_per": 97,
          "retry_history_0": 0,
          "retry_history_1": null,
          "retry_history_2": null,
          "total_dial_count": 19797,
          "retry_dial_0": 0,
          "retry_dial_1": null,
          "retry_dial_2": null,
          "callerId": "7971305710",
          "service_group": "AHM-V5",
          'retry0':[]

      },
      {
          "pilot_number": "7971647890",
          "campaignid": "94731",
          "total_dial_history": 19797,
          "total_success": 515,
          "total_failure": 19282,
          "success_per": 3,
          "failure_per": 97,
          "retry_history_0": 0,
          "retry_history_1": null,
          "retry_history_2": null,
          "total_dial_count": 19797,
          "retry_dial_0": 0,
          "retry_dial_1": null,
          "retry_dial_2": null,
          "callerId": "7971648865",
          "service_group": "AHM-V2",
          'retry0':[]

      },
      {
          "pilot_number": "7971317890",
          "campaignid": "94731",
          "total_dial_history": 19629,
          "total_success": 213,
          "total_failure": 19416,
          "success_per": 1,
          "failure_per": 99,
          "retry_history_0": null,
          "retry_history_1": 1,
          "retry_history_2": null,
          "total_dial_count": 19797,
          "retry_dial_0": 0,
          "retry_dial_1": null,
          "retry_dial_2": null,
          "callerId": "7971318862",
          "service_group": "AHM-V1",
          'retry0':[]

      },
      {
          "pilot_number": "7971728290",
          "campaignid": "94731",
          "total_dial_history": 19642,
          "total_success": 208,
          "total_failure": 19434,
          "success_per": 1,
          "failure_per": 99,
          "retry_history_0": null,
          "retry_history_1": 1,
          "retry_history_2": null,
          "total_dial_count": 19797,
          "retry_dial_0": 0,
          "retry_dial_1": null,
          "retry_dial_2": null,
          "callerId": "7971729261",
          "service_group": "AHM-V4",
          'retry0':[]

      },
      {
          "pilot_number": "8645378230",
          "campaignid": "94731",
          "total_dial_history": 9822,
          "total_success": 79,
          "total_failure": 9743,
          "success_per": 1,
          "failure_per": 99,
          "retry_history_0": null,
          "retry_history_1": 1,
          "retry_history_2": null,
          "total_dial_count": 9890,
          "retry_dial_0": 0,
          "retry_dial_1": null,
          "retry_dial_2": null,
          "callerId": "8645715030",
          "service_group": "VJVD-V8",
          'retry0':[]

      },
      {
          "pilot_number": "8645371111",
          "campaignid": "94731",
          "total_dial_history": 9809,
          "total_success": 83,
          "total_failure": 9726,
          "success_per": 1,
          "failure_per": 99,
          "retry_history_0": null,
          "retry_history_1": 1,
          "retry_history_2": null,
          "total_dial_count": 9899,
          "retry_dial_0": 0,
          "retry_dial_1": null,
          "retry_dial_2": null,
          "callerId": "8645375939",
          "service_group": "VJVD-V6",
          'retry0':[]

      },
      {
          "pilot_number": "7313772590",
          "campaignid": "94731",
          "total_dial_history": 9890,
          "total_success": 113,
          "total_failure": 9777,
          "success_per": 1,
          "failure_per": 99,
          "retry_history_0": null,
          "retry_history_1": 1,
          "retry_history_2": null,
          "total_dial_count": 9984,
          "retry_dial_0": 0,
          "retry_dial_1": null,
          "retry_dial_2": null,
          "callerId": "7313773563",
          "service_group": "IND-V3",
          'retry0':[]

      },
      {
          "pilot_number": "7313791587",
          "campaignid": "94731",
          "total_dial_history": 9809,
          "total_success": 102,
          "total_failure": 9707,
          "success_per": 1,
          "failure_per": 99,
          "retry_history_0": null,
          "retry_history_1": 1,
          "retry_history_2": null,
          "total_dial_count": 9899,
          "retry_dial_0": 0,
          "retry_dial_1": null,
          "retry_dial_2": null,
          "callerId": "7313792565",
          "service_group": "IND-V2",
          'retry0':[]

      },
      {
          "pilot_number": "7971743290",
          "campaignid": "94731",
          "total_dial_history": 19797,
          "total_success": 0,
          "total_failure": 19797,
          "success_per": 0,
          "failure_per": 100,
          "retry_history_0": null,
          "retry_history_1": 1,
          "retry_history_2": null,
          "total_dial_count": 19797,
          "retry_dial_0": 0,
          "retry_dial_1": null,
          "retry_dial_2": null,
          "callerId": "7971744265",
          "service_group": "AHM-V3",
          'retry0':[]

      },
      {
          "pilot_number": "7971304745",
          "campaignid": "94731",
          "total_dial_history": 19650,
          "total_success": 182,
          "total_failure": 19468,
          "success_per": 1,
          "failure_per": 99,
          "retry_history_0": null,
          "retry_history_1": 1,
          "retry_history_2": null,
          "total_dial_count": 19797,
          "retry_dial_0": 0,
          "retry_dial_1": null,
          "retry_dial_2": null,
          "callerId": "7971305710",
          "service_group": "AHM-V5",
          'retry0':[]

      },
      {
          "pilot_number": "7971647890",
          "campaignid": "94731",
          "total_dial_history": 19639,
          "total_success": 193,
          "total_failure": 19446,
          "success_per": 1,
          "failure_per": 99,
          "retry_history_0": null,
          "retry_history_1": 1,
          "retry_history_2": null,
          "total_dial_count": 19797,
          "retry_dial_0": 0,
          "retry_dial_1": null,
          "retry_dial_2": null,
          "callerId": "7971648865",
          "service_group": "AHM-V2",
          'retry0':[]

      },
      {
          "pilot_number": "7971317890",
          "campaignid": "94731",
          "total_dial_history": 19416,
          "total_success": 169,
          "total_failure": 19247,
          "success_per": 1,
          "failure_per": 99,
          "retry_history_0": null,
          "retry_history_1": null,
          "retry_history_2": 2,
          "total_dial_count": 19797,
          "retry_dial_0": 0,
          "retry_dial_1": null,
          "retry_dial_2": null,
          "callerId": "7971318862",
          "service_group": "AHM-V1",
          'retry0':[]

      },
      {
          "pilot_number": "7971728290",
          "campaignid": "94731",
          "total_dial_history": 19434,
          "total_success": 188,
          "total_failure": 19246,
          "success_per": 1,
          "failure_per": 99,
          "retry_history_0": null,
          "retry_history_1": null,
          "retry_history_2": 2,
          "total_dial_count": 19797,
          "retry_dial_0": 0,
          "retry_dial_1": null,
          "retry_dial_2": null,
          "callerId": "7971729261",
          "service_group": "AHM-V4",
          'retry0':[]

      },
      {
          "pilot_number": "8645378230",
          "campaignid": "94731",
          "total_dial_history": 9743,
          "total_success": 85,
          "total_failure": 9658,
          "success_per": 1,
          "failure_per": 99,
          "retry_history_0": null,
          "retry_history_1": null,
          "retry_history_2": 2,
          "total_dial_count": 9890,
          "retry_dial_0": 0,
          "retry_dial_1": null,
          "retry_dial_2": null,
          "callerId": "8645715030",
          "service_group": "VJVD-V8",
          'retry0':[]

      },
      {
          "pilot_number": "8645371111",
          "campaignid": "94731",
          "total_dial_history": 9726,
          "total_success": 68,
          "total_failure": 9658,
          "success_per": 1,
          "failure_per": 99,
          "retry_history_0": null,
          "retry_history_1": null,
          "retry_history_2": 2,
          "total_dial_count": 9899,
          "retry_dial_0": 0,
          "retry_dial_1": null,
          "retry_dial_2": null,
          "callerId": "8645375939",
          "service_group": "VJVD-V6",
          'retry0':[]

      },
      {
          "pilot_number": "7313772590",
          "campaignid": "94731",
          "total_dial_history": 9777,
          "total_success": 73,
          "total_failure": 9704,
          "success_per": 1,
          "failure_per": 99,
          "retry_history_0": null,
          "retry_history_1": null,
          "retry_history_2": 2,
          "total_dial_count": 9984,
          "retry_dial_0": 0,
          "retry_dial_1": null,
          "retry_dial_2": null,
          "callerId": "7313773563",
          "service_group": "IND-V3",
          'retry0':[]

      },
      {
          "pilot_number": "7313791587",
          "campaignid": "94731",
          "total_dial_history": 9707,
          "total_success": 86,
          "total_failure": 9621,
          "success_per": 1,
          "failure_per": 99,
          "retry_history_0": null,
          "retry_history_1": null,
          "retry_history_2": 2,
          "total_dial_count": 9899,
          "retry_dial_0": 0,
          "retry_dial_1": null,
          "retry_dial_2": null,
          "callerId": "7313792565",
          "service_group": "IND-V2",
          'retry0':[]

      },
      {
          "pilot_number": "7971743290",
          "campaignid": "94731",
          "total_dial_history": 19797,
          "total_success": 0,
          "total_failure": 19797,
          "success_per": 0,
          "failure_per": 100,
          "retry_history_0": null,
          "retry_history_1": null,
          "retry_history_2": 2,
          "total_dial_count": 19797,
          "retry_dial_0": 0,
          "retry_dial_1": null,
          "retry_dial_2": null,
          "callerId": "7971744265",
          "service_group": "AHM-V3",
          'retry0':[]

      },
      {
          "pilot_number": "7971304745",
          "campaignid": "94731",
          "total_dial_history": 19467,
          "total_success": 180,
          "total_failure": 19287,
          "success_per": 1,
          "failure_per": 99,
          "retry_history_0": null,
          "retry_history_1": null,
          "retry_history_2": 2,
          "total_dial_count": 19797,
          "retry_dial_0": 0,
          "retry_dial_1": null,
          "retry_dial_2": null,
          "callerId": "7971305710",
          "service_group": "AHM-V5",
          'retry0':[]

      },
      {
          "pilot_number": "7971647890",
          "campaignid": "94731",
          "total_dial_history": 19444,
          "total_success": 164,
          "total_failure": 19280,
          "success_per": 1,
          "failure_per": 99,
          "retry_history_0": null,
          "retry_history_1": null,
          "retry_history_2": 2,
          "total_dial_count": 19797,
          "retry_dial_0": 0,
          "retry_dial_1": null,
          "retry_dial_2": null,
          "callerId": "7971648865",
          "service_group": "AHM-V2",
          'retry0':[]

      }
  ];
  }

result:any = [];
ngOnInit(){
  this.makeJson();
}
makeJson(){
  // console.log(this.data);

 
}

}
